source 'https://github.com/Konoke/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'KeyboardAttachedToolbar_Example' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    pod 'KeyboardMan'
    pod 'SnapKit'

end
